name: CI

on:
  workflow_dispatch:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

env:
  ContinuousIntegrationBuild: 'true'

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET 8.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: | 
          8.x

    - name: Build Solution
      run: dotnet build